In [16]:
import cv2
import numpy as np

# cv2.namedWindow("preview")
vc = cv2.VideoCapture(0)

if vc.isOpened(): # try to get the first frame
    rval, frame = vc.read()
else:
    rval = False

while rval:
#     cv2.imshow("preview", frame)
    rval, frame = vc.read()
    key = cv2.waitKey(20)
    avg = [0, 0, 0]
    readings_used = 0
    for row in range(len(frame)):
        for column in range(len(frame[row])):
            if row % 10 == 0 and column % 10 == 0:
                avg += frame[row][column]
                readings_used += 1
    print(avg / readings_used)
#     print(np.median(frame, axis=0))
# if key == 27: # exit on ESC
#     break
# cv2.destroyWindow("preview")

[125.08265818 129.81331983 133.47728588]
[126.44603588 130.98770255 135.00332755]
[126.25631752 130.86323302 135.13835841]
[126.24652778 130.74667245 135.18523341]
[126.06168017 130.50217014 135.04320988]
[125.73601466 130.17539545 134.78833912]
[125.50964506 129.95437886 134.61111111]
[125.34100116 129.68074846 134.56216242]
[127.83304398 132.418451   137.4140625 ]
[135.68928434 139.35869985 138.61873071]
[142.62827932 145.4601659  150.40027006]
[143.22796103 147.03795332 154.50829475]
[144.57638889 148.13744213 154.74647955]
[147.21778549 151.28713349 157.30984761]
[135.51649306 137.07364005 147.7698206 ]
[136.69135802 137.78269676 149.4026331 ]
[130.50491898 131.20061728 143.35358796]
[193.4847608  178.46397569 166.81114969]
[203.14964313 176.48249421 148.91893326]
[229.97603202 221.64564043 212.35927855]
[120.87774884 120.12389082 114.75385802]
[146.35773534 146.89583333 145.22419946]
[138.5859375  139.57426698 137.14906443]
[115.95061728 116.77425733 116.02473958]
[104.41642554 10

[120.77131559 124.8355517  133.79185957]
[114.38941937 119.23688272 125.77493248]
[113.05155285 117.06336806 121.02517361]
[112.70833333 116.1842689  123.05608603]
[111.94637346 115.43991127 123.04118441]
[111.72646605 115.34495563 122.52242477]
[114.94386574 118.34837963 127.27604167]
[114.2772473  117.83130787 127.22188465]
[112.60816937 115.92679398 125.38233025]
[112.69675926 116.26789159 126.95143711]
[115.84133873 119.0853588  129.85358796]
[114.35180363 117.34485918 123.0935571 ]
[133.88763503 138.50024113 142.08429784]
[140.35923032 145.2501929  146.33097029]
[140.41512346 145.00163966 148.09543789]
[140.98201196 145.53481867 149.01726466]
[140.52281057 145.30150463 148.42833719]
[140.83969907 145.31539352 147.94642168]
[140.58786651 145.10440779 148.27787423]
[140.93397955 145.35291281 148.97516397]
[141.07339892 145.29841821 147.93634259]
[141.40923997 145.49546682 147.64183063]
[141.02531829 145.13917824 147.63459684]
[141.17250193 145.40075231 148.42660108]
[137.40562307 14

[58.9336902  48.66883681 90.59027778]
[130.14660494 132.4416956  148.83420139]
[112.45823688 116.57320602 119.64130015]
[139.56100502 143.37075617 143.48900463]
[138.32966821 141.21325231 142.67804784]
[140.3237365  143.4679784  140.95910494]
[149.90895062 150.96508488 145.91661844]
[133.56404321 139.35971258 146.2581983 ]
[157.48239776 162.40272955 168.69762731]
[159.26552855 161.85469715 166.97241512]
[139.03043017 141.34731867 144.33608218]
[140.36275077 141.6171875  144.99223573]
[140.05222801 143.53761574 149.95727238]
[141.45707948 144.09659529 154.61005015]
[140.2311439  144.07788387 156.13290895]
[129.66300154 134.54354745 146.02753665]
[118.33868634 123.62871335 134.1286169 ]
[126.48654514 135.19839892 149.48259066]
[141.64612269 147.62374614 159.68383488]
[140.72434414 148.93504051 164.5853588 ]
[136.15128279 143.01649306 153.0543017 ]
[134.14313272 140.95534336 149.65089699]
[130.14713542 138.34490741 151.61265432]
[142.77816358 152.2698206  170.79885224]
[153.68658372 162.2

[151.08130787 153.10325039 156.0863233 ]
[151.34437693 153.50279707 156.99122299]
[150.63107639 152.65600887 153.46985918]
[148.23688272 150.09683642 150.7077064 ]
[150.37779707 152.56548997 153.50766782]
[152.1566358  154.98900463 156.80222801]
[151.82740162 154.62012924 154.4577064 ]
[149.87336034 152.07248264 150.9296875 ]
[149.94222608 152.13999807 150.99112654]
[151.2776331  153.6087963  151.25149498]
[150.05492863 152.10431134 151.79431906]
[149.0823206  151.12606096 150.53158758]
[150.77348573 153.14747299 154.00708912]
[149.80859375 152.21325231 152.67785494]
[150.38228202 152.49739583 152.13276427]
[149.20510224 151.25892168 150.78375772]
[149.87639853 151.8168885  151.22661073]
[150.11902006 151.89448302 151.9959973 ]
[148.95572917 150.85734954 150.30135995]


KeyboardInterrupt: 